"""ui_fields

Revision ID: 8f06eaf1059a
Revises: 
Create Date: 2026-05-23 09:33:18.178791
"""
from alembic import op
import sqlalchemy as sa

revision = '8f06eaf1059a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('emoji', sa.String(length=8), nullable=False))
    op.add_column('agents', sa.Column('color', sa.String(length=32), nullable=False))
    op.add_column('agents', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('workflow_nodes', sa.Column('node_type', sa.String(length=32), nullable=False))
    op.add_column('workflow_nodes', sa.Column('label', sa.String(length=128), nullable=False))
    op.add_column('workflow_nodes', sa.Column('node_name', sa.String(length=128), nullable=False))
    op.alter_column('workflow_nodes', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_nodes', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workflow_nodes', 'node_name')
    op.drop_column('workflow_nodes', 'label')
    op.drop_column('workflow_nodes', 'node_type')
    op.drop_column('agents', 'status')
    op.drop_column('agents', 'color')
    op.drop_column('agents', 'emoji')
    # ### end Alembic commands ###
