"""add_conversations

Revision ID: d86c19c23eb3
Revises: 8f06eaf1059a
Create Date: 2026-05-23 09:33:56.239918
"""
from alembic import op
import sqlalchemy as sa

revision = 'd86c19c23eb3'
down_revision = '8f06eaf1059a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
